# -*- coding: utf-8 -*-
"""Merge RRHH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mFrmzJLliXcfCSwDepEJVuh5XCEJ_bAb
"""

import pandas as pd

df_retirement_info = pd.read_csv('https://raw.githubusercontent.com/josehiguita0722/Caso-Estudio-Anal-tica-3/main/df_renuncias.csv')
df_general_empleados = pd.read_csv('https://raw.githubusercontent.com/josehiguita0722/Caso-Estudio-Anal-tica-3/main/df_general_empleados1.csv')
df_desempeno = pd.read_csv('https://raw.githubusercontent.com/josehiguita0722/Caso-Estudio-Anal-tica-3/main/df_desempeno.csv')
df_out_time = pd.read_csv('https://raw.githubusercontent.com/josehiguita0722/Caso-Estudio-Anal-tica-3/main/df_out_time.csv')
df_in_time = pd.read_csv('https://raw.githubusercontent.com/josehiguita0722/Caso-Estudio-Anal-tica-3/main/df_in_time.csv')
df_encuesta_empleados = pd.read_csv('https://raw.githubusercontent.com/josehiguita0722/Caso-Estudio-Anal-tica-3/main/df_encuesta_empleados.csv')

data_rrhh = df_encuesta_empleados.merge(df_general_empleados,how='left',on='EmployeeID')
data_rrhh = data_rrhh.merge(df_desempeno,how='left',on='EmployeeID')
data_rrhh = data_rrhh.merge(df_in_time,how='left',on='EmployeeID').rename(columns={"horas": "hora_ingreso"})
data_rrhh = data_rrhh.merge(df_out_time,how='left',on='EmployeeID').rename(columns={"horas": "hora_salida"})
data_rrhh = data_rrhh.merge( df_retirement_info,how='left',on='EmployeeID')

data_rrhh = data_rrhh.fillna(0)

data_rrhh = data_rrhh.set_index('EmployeeID') #Convertimos el número de empleado en el índice

data_rrhh